[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
script = "scripts"
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "@chimera/=lib/chimera/src/",
    "@crytic/=lib/properties/contracts/",
    "src/=contracts/",
]
# via_ir = true
optimizer = true
optimizer_runs = 10000

no_match_test = "invariant"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
