[profile.default]
src = "contracts"
out = "artifacts"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
libs = ["node_modules", "lib"]
script = "scripts"
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "@chimera/=lib/chimera/src/",
    "@crytic/=lib/properties/contracts/",
    "src/=contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
# via_ir = true
optimizer = true
optimizer_runs = 200

ignored_warnings_from = ["contracts/test_utils/"]

fs_permissions = [
    { access = "read-write", path = "test/foundry/differential/balances.json"},
    { access = "read-write", path = "artifacts/SmartVaultManagerV6.sol/SmartVaultManagerV6.json"}
]

no_match_path = "test/foundry/invariant/*"
no_match_contract = "CryticTester|CryticToFoundry|FoundryHandler"

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api" }
arbitrum-sepolia = { key = "${ARBISCAN_KEY}", url = "https://api-sepolia.arbiscan.io/api" }

# [fuzz]
# runs = 10000

[invariant]
no_match_path = "a^"
match_contract = "FoundryTester"
fail_on_revert = false
show_progress = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
